-- upgrade --
ALTER TABLE `entry` MODIFY COLUMN `Wey` VARCHAR(500);
ALTER TABLE `entry` MODIFY COLUMN `Sender` VARCHAR(500);
ALTER TABLE `entry` MODIFY COLUMN `Organ` VARCHAR(500);
ALTER TABLE `entry` MODIFY COLUMN `Content` VARCHAR(500);
ALTER TABLE `entry` MODIFY COLUMN `Address` VARCHAR(500);
-- downgrade --
ALTER TABLE `entry` MODIFY COLUMN `Wey` VARCHAR(250);
ALTER TABLE `entry` MODIFY COLUMN `Sender` VARCHAR(250);
ALTER TABLE `entry` MODIFY COLUMN `Organ` VARCHAR(250);
ALTER TABLE `entry` MODIFY COLUMN `Content` VARCHAR(250);
ALTER TABLE `entry` MODIFY COLUMN `Address` VARCHAR(250);
